### ISSUE TITLE
Spaces and Tabs

### ISSUE THREAD

**Issue by securas** [ClementRivaille/godot-simple-sampler#4]
The scripts have mixed spaces and tabs. So, they won't run properly.

**Comment by ClementRivaille** [comment]
Okay, so after double checking, I can confirm that there isn't any tabs in the code.

_However_, this is definitely an issue I had several times lately with existing code! I'm used to indent with spaces. But often when opening a project on a new machine, I haven't yet configured Godot to use space. Thus its IDE doesn't convert spaces into tabs when opening a file, but when I start to edit some lines, their indentation turn into tabs, some are converted, some not… Leading to this error.

I think this is what happened to you. You might be able to fix it locally by applying "_Convert spaces to tabs_". If not, I'd suggest to clear the addon, then instal it again so that the source code is clean again.

But this makes me realize that using space for indentation was a mistake in the first place! Especially given that I also use an indentation of 2, where Godot default is 4. Tabs are actually [officially recommended by Godot's guidelines](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#formatting). So I'll publish a fix that replaces all spaces with tabs. This will make the plugin compatible with more projects, and easier to convert if necessary.

**Comment by ClementRivaille** [comment]
Fixed in 2.1.1: All indentations now use tabs.
